fisco:
  config:

    CasesContract: "0xed19e8abbe61bbf57ed5393d3434aa620b7afc47"
    doctorContract: ""
    patientContract: ""

    peers: "192.168.85.173:20200"
    SDKFile: "C:/code/fiscoProject/f3/src/main/resources/conf"
    pemAccountFilePath: "C:/code/fiscoProject/f3/src/main/resources/pem/0xf0c0b42c2b297d90ac89b3cecddda103f94efa81.pem"
